---
name: Labeler ğŸ·ï¸

on:
  - pull_request_target

jobs:
  labeler:
    name: Labeler
    uses: voxpupuli/crafty/.github/workflows/labeler.yml@main
    with:
      allowed_owner: ${{ github.repository_owner }}
